### ISSUE TITLE
Question on multi-agent pose

### ISSUE THREAD

**Issue by jpoberhauser** [danbider/lightning-pose#103]
Hello, 

Not an issue, so feel free to label as question! 

Thanks for releasing lightning-pose. Is there a way to make it work with multi-agent videos, or is the added complexity of handling spatiotemporal constraints on different tracklets the difficult part here?

**Comment by themattinthehatt** [comment]
Hey @jpoberhauser, thanks for checking out the repo!

Currently we do not support multi-agent pose estimation. While we think the techniques we've introduced (context architecture, unsupervised losses) will work in this problem setting, we have not yet pursued this.

However, we have been experimenting with the ensemble kalman smoother in the multi-agent setting with good results, so if you have some multi-agent data I'd suggest trying that out. You can find the repo here: https://github.com/paninski-lab/eks.

The repo contains example scripts, including this most basic one that just uses temporal information (no pose pca/multiview information): https://github.com/paninski-lab/eks/blob/main/scripts/singlecam_example.py. This would be the easiest place to start.

**Comment by jpoberhauser** [comment]
Thanks for the info. I will certainly take a look.
