### ISSUE TITLE
lit-pose crashes while using .avis

### ISSUE THREAD

**Issue by jackransomlovell** [danbider/lightning-pose#107]
`trainer.fit` will crash if the unlabeled data are in `.avi` format, just hangs without any errors. 

This is obviously dealt with in the io module with a couple of asserts and booleans, but before digging into the details I figured asking why here would be worth while.

**Comment by themattinthehatt** [comment]
hey @jackransomlovell thanks for raising the issue, sounds like we need some more assertions in the code

the issue is with the DALI package, it currently only supports a limited subset of encoding/chroma formats. not sure what their long-term plan is for supporting more formats

**Comment by themattinthehatt** [comment]
here's a function we use to reencode the videos (must have ffmpeg installed):
```python
import os
import subprocess

def reencode_video(input_file: str, output_file: str) -> None:
    """reencodes video into H.264 coded format using ffmpeg from a subprocess.

    Args:
        input_file: abspath to existing video
        output_file: abspath to to new video

    """
    # check input file exists
    assert os.path.isfile(input_file), "input video does not exist."
    # check output is mp4
    assert output_file.endswith(".mp4"), "output video must in with '.mp4'"
    # check directory for saving outputs exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    ffmpeg_cmd = f'ffmpeg -i {input_file} -c:v libx264 -pix_fmt yuv420p -c:a copy -y {output_file}'
    subprocess.run(ffmpeg_cmd, shell=True)
```

**Comment by jackransomlovell** [comment]
> hey @jackransomlovell thanks for raising the issue, sounds like we need some more assertions in the code
 
I just commented those assertions out, to confirm on my end things they work pretty well from what I recall. 

Thank you for sharing the function above, and developing this library, we will certainly put both to good use!
