### ISSUE TITLE
Feature: add support for multiple (non-fused) camera views

### ISSUE THREAD

**Issue by themattinthehatt** [danbider/lightning-pose#120]
The current package only supports multiview setups that have fused views across cameras into a single frame. This does not scale well past 2-4 views.

**Comment by YitingChang** [comment]
We're interested in the multiview feature for separated data streams. We would like to track monkey hands in 3D from 6 camera views.

**Comment by themattinthehatt** [comment]
@YitingChang thanks for reaching out! We've wrapped up this feature and are working on docs now, I'll reach out to you when they're ready.

**Comment by mariusosswald** [comment]
Hello, we are also highly interested in the multiview feature for separate videos of different camera angles. Is there any update about the feature and documentation by now?

**Comment by NgD-Huy** [comment]
Hello, any updates on the feature at this point?

**Comment by themattinthehatt** [comment]
Hi everyone, thanks for your interest in this feature (and your patience). I wanted to let you know that we have a beta version up and running and documented. The current version will allow you to fit supervised and context models on mulitple synchronized camera views. 

In order to use this feature, you will need to pull updates and switch to the `dynamic_crop` branch of the repo:
```
git fetch
git checkout dynamic_crop
```

The documentation describing the data layout and how to run training and inference can be found here:
https://lightning-pose.readthedocs.io/en/dynamic_crop/source/user_guide_advanced/multiview_separate.html

Please let us know if you start using this feature! We are eager to support you all through bug fixes, feature requests, guidance on training, etc. Reach out to us on discord if you just want to chat, or if you run into a bug please raise a separate github issue.

We are currently working on several new features that you all will be interested in as well:
* implement unsupervised losses for the multiview case
* in many of these multiview setups the animal is moving around in an environement much larger than itself. It therefore makes sense to have a two-stage pipeline, where the animal is first localized within each view, and then a region around the animal is cropped out in 3 dimensions. In the second stage a standard pose estimator is run on this cropped version, leading to increased precision in the pose estimates.

I will keep everyone updated on our progress with these. 

@danbider @farzad-ziaie @Selmaan @YitingChang @mariusosswald @NgD-Huy @ankitvishnu23

**Comment by NgD-Huy** [comment]
Thank you for the update!

**Comment by DavidGill159** [comment]
Thanks for the update! @themattinthehatt I have a 4 camera setup of an arena with a mouse. Currently, we use Deeplabcut to track the animal across the different cameras and then triangulate the landmarks in 3D afterwards. Will this beta multi-camera LP version produce landmark data for each camera that I could use to similarly triangulate? If the current beta is supervised only, then how does it compare to existing supervised models like Deeplabcut? Thanks in advance.

**Comment by themattinthehatt** [comment]
@DavidGill159 

> how does it compare to existing supervised models like Deeplabcut?
Right now we train a single LP network across all available views. This network then processes videos from one view at a time. Afterwards you can do the triangulation - so in this sense the workflow is the same as DLC. We have yet to benchmark the supervised-only version vs DLC or SLEAP in this multiview setup, but we are working on that. My guess, based on our experiments in the [LP paper](https://www.biorxiv.org/content/10.1101/2023.04.28.538703v2), is that the supervised performance will be on par with DLC. The current multiview LP implementation _does_ allow for context frames, so if you have a dataset that contains a lot of brief occlusions I think the LP context model (TCN) would do much better on those frames than DLC. 

> for the csv_file section, do I need to list every csv for every labelled video?
For now the expected format is actually a hybrid of the two options: there should be one csv _per view_ that contains the labels from multiple videos. So if you have 4 views you should have 4 csv files: `CollectedData_camera_1`, ... `CollectedData_camera_2` (though the names themselves are arbitrary).

Did you use the DLC->LP conversion script from the repo? We haven't updated that to work with multiview datasets. So for now you'll have to manually split your CollectedData.csv file into the 4 separate files. The important thing to verify is that row `n` in each file all correspond to the same video/frame number.

I'll also mention that technically speaking you could train a "singleview" model using your current CollectedData.csv file. However, once the unsupervised losses become available then it will be required to have the csv split by view so that during training we can ensure that corresponding views from the same video/frame are handled properly.

Please let me know if you have any other questions!

**Comment by DavidGill159** [comment]
> @DavidGill159
> 
> > how does it compare to existing supervised models like Deeplabcut?
> 
> Right now we train a single LP network across all available views. This network then processes videos from one view at a time. Afterwards you can do the triangulation - so in this sense the workflow is the same as DLC. We have yet to benchmark the supervised-only version vs DLC or SLEAP in this multiview setup, but we are working on that. My guess, based on our experiments in the [LP paper](https://www.biorxiv.org/content/10.1101/2023.04.28.538703v2), is that the supervised performance will be on par with DLC. The current multiview LP implementation _does_ allow for context frames, so if you have a dataset that contains a lot of brief occlusions I think the LP context model (TCN) would do much better on those frames than DLC.
> 
> > for the csv_file section, do I need to list every csv for every labelled video?
> 
> For now the expected format is actually a hybrid of the two options: there should be one csv _per view_ that contains the labels from multiple videos. So if you have 4 views you should have 4 csv files: `CollectedData_camera_1.csv`, ... `CollectedData_camera_4.csv` (though the names themselves are arbitrary).
> 
> Did you use the DLC->LP conversion script from the repo? We haven't updated that to work with multiview datasets. So for now you'll have to manually split your CollectedData.csv file into the 4 separate files. The important thing to verify is that row `n` in each file all correspond to the same video/frame number.
> 
> I'll also mention that technically speaking you could train a "singleview" model using your current CollectedData.csv file. However, once the unsupervised losses become available then it will be required to have the csv split by view so that during training we can ensure that corresponding views from the same video/frame are handled properly.
> 
> Please let me know if you have any other questions!

Thank you for the prompt reply! I reformatted everything as you recommended. When running training I get this error returned (see attached screenshot). 
![image](https://github.com/danbider/lightning-pose/assets/116177739/0919af8a-ef00-4415-9628-56a98619e99e)

**Comment by themattinthehatt** [comment]
haven't seen that one before. can you send/show a screenshot of one of your csv files (with the header)?
also, did you update the config file to list all 4 csv files?

**Comment by DavidGill159** [comment]
> haven't seen that one before. can you send/show a screenshot of one of your csv files (with the header)? 

Sure, here is a screenshot for 1 of the cameras:
![image](https://github.com/danbider/lightning-pose/assets/116177739/0517b9d5-ab7e-472d-acec-daa3a803a040)

> did you update the config file to list all 4 csv files?
Yep, I did.

**Comment by themattinthehatt** [comment]
It seems the DLC->LP conversion didn't succeed: you can see in column B what are supposed to be the snout x labels are instead the camera names (and similar for column C). And because of that, the final columns (X and Y) don't have any entries. My guess is this is why you're getting that error (since the error you got is consistent with a string not being a number).

The DLC->LP converter should be able to handle this type of data but clearly something went wrong. If you send me the labels from one of your DLC labeled data folders I can try to fix it. Do you have both csv and h5 files for the labeled data?

**Comment by DavidGill159** [comment]
Hi, I have returned to training a 3D supervised model. When running training I get this error. Looking at the train_hydra file, is this an issue with finding the frame images? See attached the error and my lightningpose directory; within each camera folder are subfolders for different trials, is this the issue? i.e. should all the extracted frames across trials be pooled together within 1 folder? - this would be a headache to sort out if so, as some of the same frame numbers may have been extracted across different trials.
![image](https://github.com/danbider/lightning-pose/assets/116177739/27e5b2c8-c1bf-413d-9a80-6d1e1cf66c32)
![image](https://github.com/danbider/lightning-pose/assets/116177739/d52b6db6-7a04-4590-a2b4-576fa8a98881)

**Comment by themattinthehatt** [comment]
@DavidGill159 did you post a follow-up question here? I got an email but for some reason I'm not seeing any new activity in this thread.

**Comment by DavidGill159** [comment]
> @DavidGill159 did you post a follow-up question here? I got an email but for some reason I'm not seeing any new activity in this thread.

Hi yes I thought I had resolved it but I am still having an issue:
I created a new network to produce 3D data from 4 separate camera streams, considering our previous discussion ^ i.e. there are 4 CSVs, 1 for each camera, containing the labelled frames for different videos; the same frames were extracted for each camera view. However, I am getting this error when attempting to train a supervised model.
![image](https://github.com/danbider/lightning-pose/assets/116177739/445d03fd-428b-4e27-b3e7-35257f1116e5)

**Comment by themattinthehatt** [comment]
Based on the error traceback the code is attempting to create a `HeatmapDataset` when it should actually be building a `Multiview HeatmapDataset`. There are two potential reasons for this off the top of my head:

1. you are on the wrong branch of the LP repo - are you on `dynamic_crop`?
2. you did not include the `data.view_names` field in your config file (see here: https://lightning-pose.readthedocs.io/en/dynamic_crop/source/user_guide_advanced/multiview_separate.html#the-configuration-file). for now this is way the code recognizes your data as a multiview dataset

**Comment by DavidGill159** [comment]
Hi, yes I am using the dynamic_crop. 

Here is my config:
![image](https://github.com/danbider/lightning-pose/assets/116177739/678fc5d1-f605-4c47-aa66-310ef802ec27)

**Comment by DavidGill159** [comment]
Hi, tried that but still getting the same error when trying to train. 
![image](https://github.com/danbider/lightning-pose/assets/116177739/90661d26-9994-4e8c-97a9-1a635c5ecc15)

**Comment by themattinthehatt** [comment]
@DavidGill159 whenever you start training there should be a printout of the various config options - can you copy/paste that here?

**Comment by themattinthehatt** [comment]
Very strange, I don't understand why you're not able to build a `MultiviewHeatmapDataset`. I would suggest debugging by putting some print statements into the actual code itself to get a better idea of what's going wrong. The relevant function is [get_dataset](https://github.com/danbider/lightning-pose/blob/dynamic_crop/lightning_pose/utils/scripts.py#L80) - based on your error traceback this function is returning a `HeatmapDataset`. So at the top of this function put a `print(cfg)`, or otherwise try to understand which part of the `if/else` statement you're entering and why. You can see that a `MultiviewHeatmapDataset` will be returned if `cfg.data` contains the field `view_names` and the length of that field is greater than 1 (meaning multiple views), which does seem to be the case based on your config above.

**Comment by DavidGill159** [comment]
Ok I have figured out what is going wrong. When calling training, my powershell is using the scripts.py from the path: 
"/mnt/c/Users/X48823DG/lightning-pose**/Pose-app/lightning-pose/lightning_pose/utils/scripts.py"**

updating to the dynamic crop branch in my LP environment is updating the scripts.py at this destination instead:
"/mnt/c/Users/X48823DG/lightning-pose**/lightning_pose/utils/scripts.py"**

**Comment by themattinthehatt** [comment]
ah ok - are you trying to run the multiview training from the command line or from the app?

**Comment by DavidGill159** [comment]
Through the command line as normal

**Comment by DavidGill159** [comment]
hi, perhaps the best solution is to remove the app installation altogether (I don't use it) so that only the local installation destination is used?

**Comment by DavidGill159** [comment]
So I removed LightningPose altogether and did a clean installation; the pytest ran successfully with 74 passed, and 14 warnings. I did not install the app this time. The branch has been successfully updated to dynamic crop. When running training I get this error now. 
![image](https://github.com/danbider/lightning-pose/assets/116177739/3c60ac07-783e-4fb7-819d-5bdf853123ea)

**Comment by YitingChang** [comment]
@themattinthehatt Thank you so much for the updates! 

I'm trying to run the multiview training from the command line but get this error.

![multiview_error1](https://github.com/danbider/lightning-pose/assets/32401112/0ce2e49c-792e-4b4d-8088-613e36520445)

Here is my configuration:

--------------------
data parameters
--------------------
image_orig_dims: {'height': 960, 'width': 960}
image_resize_dims: {'height': 256, 'width': 256}
data_dir: /home/yiting/Documents/LP_projects/LP_240613
video_dir: /home/yiting/Documents/LP_projects/LP_240613/videos_checked
csv_file: ['camBL.csv', 'camBo.csv', 'camBR.csv', 'camTL.csv', 'camTo.csv', 'camTR.csv']
view_names: ['camBL', 'camBo', 'camBR', 'camTL', 'camTo', 'camTR']
downsample_factor: 2
num_keypoints: 12
keypoint_names: ['index_Tip', 'index_DIP', 'index_PIP', 'middle_Tip', 'middle_DIP', 'middle_PIP', 'ring_Tip', 'ring_DIP', 'ring_PIP', 'small_Tip', 'small_DIP', 'small_PIP']
mirrored_column_matches: None
columns_for_singleview_pca: [0, 1, 3, 4, 5, 6, 7, 8]

--------------------
training parameters
--------------------
imgaug: dlc
train_batch_size: 12
val_batch_size: 24
test_batch_size: 24
train_prob: 0.8
val_prob: 0.1
train_frames: 1
num_gpus: 1
num_workers: 4
early_stop_patience: 3
unfreezing_epoch: 20
min_epochs: 300
max_epochs: 300
log_every_n_steps: 10
check_val_every_n_epoch: 5
gpu_id: 0
rng_seed_data_pt: 0
rng_seed_model_pt: 0
lr_scheduler: multisteplr
lr_scheduler_params: {'multisteplr': {'milestones': [150, 200, 250], 'gamma': 0.5}}

--------------------
model parameters
--------------------
losses_to_use: ['temporal', 'pca_singleview', 'pca_multiview']
backbone: resnet50_animal_ap10k
model_type: heatmap_mhcrnn
heatmap_loss_type: mse
model_name: test
checkpoint: None

--------------------
dali parameters
--------------------
general: {'seed': 123456}
base: {'train': {'sequence_length': 12}, 'predict': {'sequence_length': 48}}
context: {'train': {'batch_size': 6}, 'predict': {'sequence_length': 48}}

--------------------
losses parameters
--------------------
pca_multiview: {'log_weight': 5.0, 'components_to_keep': 3, 'epsilon': None}
pca_singleview: {'log_weight': 5.0, 'components_to_keep': 0.99, 'epsilon': None}
temporal: {'log_weight': 5.0, 'epsilon': 20.0, 'prob_threshold': 0.05}

--------------------
callbacks parameters
--------------------
anneal_weight: {'attr_name': 'total_unsupervised_importance', 'init_val': 0.0, 'increase_factor': 0.01, 'final_val': 1.0, 'freeze_until_epoch': 0}

**Comment by themattinthehatt** [comment]
@YitingChang we're still working on getting the unsupervised losses working for the mutliview case, so for now you'll have to just train a fully supervised model by setting `model.losses_to_use: []` in the config file

**Comment by DavidGill159** [comment]
> ah ok - are you trying to run the multiview training from the command line or from the app?

Hi, It goes through the command line. I solved that issue by re-installing LP without the app. However, I am now facing a new error:
![image](https://github.com/danbider/lightning-pose/assets/116177739/8e283002-2642-4f1a-a567-22a402376b00)

**Comment by YitingChang** [comment]
> > ah ok - are you trying to run the multiview training from the command line or from the app?
> 
> Hi, It goes through the command line. I solved that issue by re-installing LP without the app. However, I am now facing a new error: ![image](https://private-user-images.githubusercontent.com/116177739/339710873-8e283002-2642-4f1a-a567-22a402376b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODc3OTAsIm5iZiI6MTcxODM4NzQ5MCwicGF0aCI6Ii8xMTYxNzc3MzkvMzM5NzEwODczLThlMjgzMDAyLTI2NDItNGYxYS1hNTY3LTIyYTQwMjM3NmIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNzUxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmM2NTFjNWVmMDg0MmJjZjE2ZTI2Njk0YTAzMTg3MDFhYWRhMjgxMmY2NWU0NTlhMTZkNWY5N2Y3OTgzMjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4eLgfZ1Clg0eD0KgBGBallyPd6-Lwa8n4VZDv_ZpVFI)

I'm getting the same error.

**Comment by themattinthehatt** [comment]
ok not sure why this is popping up now since I haven't updated this branch in a few months - I'll look into this as soon as possible (might take a couple days) and get back to you. Thanks for your patience!

**Comment by themattinthehatt** [comment]
@DavidGill159 @YitingChang I fixed the error and pushed the code to the `dynamic_crop` branch. I added some new tests and everything looks to be working fine, but please let me know if you run into any other issues.

@YitingChang I also merged in all the newest updates from `main`, including the hand backbone, so you should be set to use that backbone to train a multiview model now.

**Comment by DavidGill159** [comment]
> @DavidGill159 @YitingChang I fixed the error and pushed the code to the `dynamic_crop` branch ([5829fbe](https://github.com/danbider/lightning-pose/commit/5829fbe910c2cd3eac845dc5bd50f4750e5e7063)). I added some new tests and everything looks to be working fine, but please let me know if you run into any other issues.
> 

Great all working now! 👍

**Comment by YitingChang** [comment]
Thank you! I'm training a multiview model with the hand backbone now. Everything looks fine so far!

**Comment by DavidGill159** [comment]
> @DavidGill159 awesome, glad to hear! How is the baseline model working for you so far?
> 

It looks good! At least on par with DeepLabCut if not better. To clarify, without applying the unsupervised losses, how is the multi-camera model different to just running all the different camera's data in a 'single-camera' model? (i.e. unaware of multiple cameras, like DLC). 


> No progress on the multiview pca loss yet, we've been busy wrapping up the final touches on the lightning pose publication (to appear in Nature Methods tomorrow, June 25th!!). Will hopefully be getting to it soon. Thanks for your patience.

Ah that's great! looking forward to it! :)

**Comment by themattinthehatt** [comment]
> To clarify, without applying the unsupervised losses, how is the multi-camera model different to just running all the different camera's data in a 'single-camera' model? (i.e. unaware of multiple cameras, like DLC).

That is correct - it's the unsupervised multiview loss that will link all the views together (eventually we'll do the same pca multiview loss on the labeled data as well)

**Comment by themattinthehatt** [comment]
Hi everyone, this feature is officially merged into `main`!! And will soon be part of the LP v1.5.0 PyPI release. Thanks for your patience, and thanks to @farzad-ziaie @Selmaan for their work on this.

I'm going to close this issue now, if you run into additional issues once you have moved over to the updated `main` branch please create a new issue.

I'm also very curious to see how the code is working for people, so please feel free to drop a line in the [discord](https://discord.gg/tDUPdRj4BM) if you want to share some cool results (or not so cool results, discord is also a good place for debugging :smile:)

**Comment by wyclearnpy** [comment]
> > @DavidGill159你在这里发布了后续问题吗？我收到了一封电子邮件，但不知为何我没有看到此主题中有任何新活动。
> 
> 嗨，是的，我以为我已经解决了这个问题，但我仍然遇到一个问题： 考虑到我们之前的讨论，我创建了一个新网络来从 4 个独立的摄像机流生成 3D 数据 ^ 即有 4 个 CSV，每个摄像机 1 个，包含不同视频的标记帧；每个摄像机视图都提取了相同的帧。但是，我在尝试训练监督模型时遇到了这个错误。 ![图像](https://private-user-images.githubusercontent.com/116177739/333651010-445d03fd-428b-4e27-b3e7-35257f1116e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjcwOTgsIm5iZiI6MTcyODQ2Njc5OCwicGF0aCI6Ii8xMTYxNzc3MzkvMzMzNjUxMDEwLTQ0NWQwM2ZkLTQyOGItNGUyNy1iM2U3LTM1MjU3ZjExMTZlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwOTM5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmUxNmU3ZDU0OTNmY2Y0Y2I2NDA4YzU0ODAwNzUzNDFhMzZkMTNkMGI0YmQ3YjE1YWVjZWVjOTdjYmYzNjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vPVJVUXzXH2b59xt_L0M8LauHvA8JYntHdUsd6NTBPA)
> 
> 我的数据按照所附的屏幕截图进行组织：
> 
> ![图像](https://private-user-images.githubusercontent.com/116177739/333653546-960f9473-b6bf-4edb-9562-9d58cb60aed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjcwOTgsIm5iZiI6MTcyODQ2Njc5OCwicGF0aCI6Ii8xMTYxNzc3MzkvMzMzNjUzNTQ2LTk2MGY5NDczLWI2YmYtNGVkYi05NTYyLTlkNThjYjYwYWVkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwOTM5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWM2NDg4MTM4YjIzMmI0Yzg0ZmEyNjdlNzJhMWUyYzIyOWEwNWViZjJlOGNmMGI5ZDM0NmM1NGMyMDQ1ZTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s8kq2W0CLMbh-n3tIaiivE2RfLunKqeTRZkOZw6aOto)
I also encountered this problem, what caused it?
