### ISSUE TITLE
Query regarding use of Filtered_predictions in LightningPose model

### ISSUE THREAD

**Issue by ReetKaur15** [danbider/lightning-pose#133]
Hi Team,

I want to know, what the post-processing approach used by LightningPose ? Also, I have following queries:
1. Does lightningPose use filtered_predictions options in its model as a post-processing step as done by the DeeplabCut model? 
2. If yes, could you please explain, is it using filtered predictions by default (we cannot disable it) or can we change this setting in the config file (if yes, where in the config file)? 

Many thanks in advance,

**Comment by themattinthehatt** [comment]
We don't implement any post-processing in the lightning pose repo; all of your results are raw predictions from the network.

If you're interested in a good post-processor (and have the extra compute) I'd recommend an ensembling method that we've had very good luck with:
* see results in preprint here: https://www.biorxiv.org/content/10.1101/2023.04.28.538703v1.full.pdf
* see repo here: https://github.com/paninski-lab/eks

tagging @colehurwitz, he's the lead developer on that one
