### ISSUE TITLE
multiple csv files

### ISSUE THREAD

**Issue by Wulin-Tan** [danbider/lightning-pose#136]
Hi, lightning pose team
lightning pose is a great tool. and it is very important to my project.
I used to use deeplabcut before, and now I have multiple videos with multiple csv files. 
How can I move on with lightning pose?
should I put all the csv files into one or should I train one model with one csv file?
Hoping for your suggestions.

**Comment by themattinthehatt** [comment]
Hi @Wulin-Tan, thanks for checking out Lightning Pose! If you would like to convert a DLC project to Lightning Pose, please see the docs here: https://lightning-pose.readthedocs.io/en/latest/source/user_guide/directory_structure.html#converting-dlc-projects-to-lightning-pose-format

Please let me know if you run into any issues with this, or if any part of the documentation is unclear.

**Comment by Wulin-Tan** [comment]
> Hi @Wulin-Tan, thanks for checking out Lightning Pose! If you would like to convert a DLC project to Lightning Pose, please see the docs here: https://lightning-pose.readthedocs.io/en/latest/source/user_guide/directory_structure.html#converting-dlc-projects-to-lightning-pose-format
> 
> 
> 
> Please let me know if you run into any issues with this, or if any part of the documentation is unclear.

yes,with the converting script,it works perfect! Thank you!
