### ISSUE TITLE
Starts training from specific checkpoint

### ISSUE THREAD

**Issue by NgD-Huy** [danbider/lightning-pose#143]
Hello and happy Friday,

I couldn't find these topics in the documentation so some clarification would be appreciated. 

When adding new videos to an existing project,
1. Is it possible to label novel videos using the current model or do we still need to label frames?
2. Is it possible to continue training from an existing checkpoint?

Thank you very much for your work!

**Comment by themattinthehatt** [comment]
Hi @NgD-Huy, thanks for the questions.

1. can you clarify what you mean by "label novel videos" - you mean as a human, or if the model can label novel videos? If you're asking about the model, yes absolutely once you have a trained model you can run inference on any new video you wish; see docs here: https://lightning-pose.readthedocs.io/en/latest/source/user_guide/inference.html

2. yes! in the config file, under the "model" section, add a new parameter named "checkpoint", and set the parameter to the absolute path of whatever checkpoint file you want

config.yaml:
```
model:
  checkpoint: /path/to/model.ckpt
```

I will make sure to update the documentation to include this info!

**Comment by NgD-Huy** [comment]
That answered all of my questions! Thank you very much!

**Comment by themattinthehatt** [comment]
closed by #147
