### ISSUE TITLE
any manual refining and re-training function in lightning pose?

### ISSUE THREAD

**Issue by Wulin-Tan** [danbider/lightning-pose#144]
hi, lightning pose team
is there any manual refining and re-training function in lightning pose if I feel unsatisfied with the prediction?

**Comment by themattinthehatt** [comment]
We don't have manual refinement built in to the lightning-pose package itself, but we have been working on a lightning pose app that allows you to label new frames and retrain models; check out the repo here: https://github.com/Lightning-Universe/Pose-app

Happy to answer any questions about it! (preferrably in the Pose-app issues section)
