### ISSUE TITLE
Set different temporal loss parameters for each body parts

### ISSUE THREAD

**Issue by Wei21st** [danbider/lightning-pose#148]
Hi lightning-pose team,

I have multiple body parts labeled. But some of them have a very limited range of movement (1/5 of width of the video) but others moves at a much larger range (nearly across the width of the video) . I tried to use same epsilon for all of the body parts but it seems not working well. Can I set different temporal loss parameters for each boday parts?

Or do you have any suggestions on how I can adjust the parameters?

Another alternative I am thinking is to train two models for the body parts. But it would definetly make it easier for me to just label once, train once and infer once.

Thanks! Appreciate your reply!

Best,
Nora

**Comment by themattinthehatt** [comment]
Hi Nora, yes this is indeed possible, all you need to do is use a list of epsilons rather than a single value; see the example config file here: https://github.com/danbider/lightning-pose/blob/v1.2.2/scripts/configs/config_mirror-mouse-example.yaml#L162
