### ISSUE TITLE
support for avi formats

### ISSUE THREAD

**Issue by Wei21st** [danbider/lightning-pose#150]
Hi lightning-pose team.

Our lab collects video using avi formats and it seems the lightning-pose only support the mp4 format (correct me if i am wrong!). Could you add features to support avi formats as Deeplabcut did? It seems the online video format convert tools are not free. This will make our work much easier. 

Thank you so much!

Best,
Nora

**Comment by themattinthehatt** [comment]
Hi Nora, thanks for your question.

In short, you can easily convert your videos to a format that lightning pose will accept using ffmpeg; you can find an example function [here](https://github.com/Lightning-Universe/Pose-app/blob/d8b1069667e6d84b9be8ea63d4aba4a86eefbd7b/lightning_pose_app/backend/video.py#L15)

A longer answer to your question: .avi is a container format that supports multiple types of data - video and audio streams, metadata, subtitles, etc. The video stream format itself is the one that matters, in our case for the DALI pipeline. The video format needs to be h.264, and the function that I linked above will covert the video stream to this format for you.

**Comment by Wei21st** [comment]
Thanks Matt. I've solve the problem using the code you provided.
