### ISSUE TITLE
can lightning pose predict images?

### ISSUE THREAD

**Issue by Wulin-Tan** [danbider/lightning-pose#156]
Hi, lightning pose team

I have trained a lightning pose model. Can it predict some images (png, jpg...) from consecutive frames instead of a video?

Wulin

**Comment by themattinthehatt** [comment]
@Wulin-Tan do your images have hand labels associated with them, or are they unlabeled images?

**Comment by Wulin-Tan** [comment]
Hi, @themattinthehatt 
they are unlabled images. I want to use the already trained model to predict labels on them.

**Comment by themattinthehatt** [comment]
Ah I see. There are two options, both a bit clunky, but either should work.

Option 1: turn all of the images into a single mp4 file using `ffmpeg`, and then run inference on this video. Note this will not work if you are using a context model (or rather, it will work but you would need to extract the predictions from the resulting csv file that correspond to the middle frame of each 5-frame chunk)

Option 2: create a csv file that is a fake "labels" file. Each row of this file would contain the relative path to frame in the first column, and then zeros (say) in all of the remaining columns that indicate the (x, y) coordinates. Then you can replicate the the dataset prediction steps starting here: https://github.com/danbider/lightning-pose/blob/a6b04e54117da2cf01f2df918f9aed58f605c514/lightning_pose/train.py#L202
The process is:
1. load your config file, then update it to remove data augmentations
2. build the imgaug transform (which will only resize, no other augmentations), then the dataset, then the data module
3. pass that dataset to the `predict_dataset` function, which will save predictions on all of the frames within that data module to a csv file

Let me know if you try either or these. We can work on building a data loader that doesn't require the csv file, but we have quite a development backlog right now so won't be able to work on something like that too soon.

**Comment by Wulin-Tan** [comment]
Hi, @themattinthehatt 
I haven't tried yet. But I might do that this week.
in option 1, do you mean when predicting new images by context model, I need to upload consecutive images like 2+1+2(my target image is in the center)?

**Comment by themattinthehatt** [comment]
oh good point - the mp4 file would be a bit trickier with a context model. you are correct that you would need to include 5 consecutive images, and only use the predictions for the center image. the predictions for the non-center images would include frames from two disjoint subsets of images, so you would need to throw those away. if you're ok keeping track of this then the mp4 file is probably the fastest route, but the second option is definitely better practice

**Comment by themattinthehatt** [comment]
@Wulin-Tan curious if you were able to get something working - if so I'll close this issue for now.

**Comment by Wulin-Tan** [comment]
hi, @themattinthehatt 
option 1 works for me. but still it is a little bit complicated that I have to extract images from videos and synthesize videos again. So finally I settle down to predict the whole videos directly and pick and frames I want. this is more straightforward for me. And thank you for your suggestion.
