### ISSUE TITLE
match num_workers with batch size

### ISSUE THREAD

**Issue by Wulin-Tan** [danbider/lightning-pose#164]
Hi, lightning pose team
I can run LP on a GPU with more memory(48g vs 80g), I want to increase the batch size. Do I need to increase num_workers(16 is default in the config)? assuming I have enough cpu cores.

**Comment by themattinthehatt** [comment]
@Wulin-Tan just checking in on this, did you find any speedups by increasing `num_workers`?

**Comment by Wulin-Tan** [comment]
Hi, @themattinthehatt 
I tried but the speedyup is not obvious. I guess the reason might be that:
the major part of the process is done on GPU, so the speedup by num_workers is not that significant.
