### ISSUE TITLE
ModuleNotFound: hydra

### ISSUE THREAD

**Issue by themattinthehatt** [danbider/lightning-pose#173]
So I removed LightningPose altogether and did a clean installation; the pytest ran successfully with 74 passed, and 14 warnings. I did not install the app this time. The branch has been successfully updated to dynamic crop. When running training I get this error now. 
![image](https://github.com/danbider/lightning-pose/assets/116177739/3c60ac07-783e-4fb7-819d-5bdf853123ea)

_Originally posted by @DavidGill159 in https://github.com/danbider/lightning-pose/issues/120#issuecomment-2166097678_

**Comment by themattinthehatt** [comment]
how did you install - did you run `pip install -e .` from inside the `lightning-pose` directory?

**Comment by DavidGill159** [comment]
ah yes my bad, I skipped the dependencies step by mistake. all solved now thank you
