### ISSUE TITLE
Fail to make videos after running inference

### ISSUE THREAD

**Issue by YitingChang** [danbider/lightning-pose#178]
Hi Lightning Pose Team,

I was trying to run inference on new videos but got a TypeError about video frame rate (fps). The format of the videos should be correct since I reencoded them into h.264 codec. The results were successfully saved in a csv file. I would appreciate any suggestions. Thank you!
![Inference_issue](https://github.com/danbider/lightning-pose/assets/32401112/3002539b-e4dd-49c3-8255-0b45d26e1db4)

**Comment by themattinthehatt** [comment]
I've run into this issue before on some other setups - it's an issue with moviepy and/or ffmpeg. Here are some suggestions from others: https://stackoverflow.com/questions/68032884/getting-typeerror-must-be-real-number-not-nonetype-whenever-trying-to-run-wr

What version of `moviepy` are you using?

**Comment by themattinthehatt** [comment]
seems like
```
pip uninstall moviepy
pip install moviepy
```
is a good first place to start?

**Comment by YitingChang** [comment]
The version of moviepy was 1.0.3. 

Thanks for sharing the information. Reinstalling moviepy and ffmpeg doesn't work for me. But downgrading the decorator package to 4.0.2 works!

**Comment by themattinthehatt** [comment]
ah ok good to know! glad that worked out.
