### ISSUE TITLE
Out of memory error with Multi-camera context network. 

### ISSUE THREAD

**Issue by DavidGill159** [danbider/lightning-pose#182]
Hi, I am trying to train a multi-camera-context-supervised network using separate camera data streams (not fused). I have successfully trained a multi-camera supervised network using your dynamic_crop branch. However, when training an equivalent context network I get an out-of-memory error. To deal with this, I changed the train_batch_size from 16 to 8 but the issue remains. 

**GPU specifications:** NVIDIA GeForce RTX 4080 with Cuda 11.6.

**Comment by themattinthehatt** [comment]
@DavidGill159 the only two options here are to reduce `train_batch_size` further or use a GPU with more memory. The context model will require ~5x more memory than the non-context model.

How big are your frames, and what are you resizing them to?

**Comment by DavidGill159** [comment]
Hi, 
image_orig_dims: 1024x1280
image_resize_dims: 384x384

**Comment by themattinthehatt** [comment]
Have you tried chaning your resize dims to 256x256? Maybe worth trying in the non-context model first to see if you get results that you like. If 256x256 works for you the model will take up way less memory, and you could train the context model with a batch size larger than 4.

**Comment by DavidGill159** [comment]
I will give that a go and get back to you :)

**Comment by DavidGill159** [comment]
Hi, this worked. Thank you for the help.
