### ISSUE TITLE
axios error: network error?

### ISSUE THREAD

**Issue by Chrysovalantis000** [danbider/lightning-pose#185]
We get an error when trying to upload full videos unless we break them down in small chunks, however this error is new because in the past we used a different computer and this did not happen. Our new computer is more powerful but this weird thing happens.

We also trying to understand in regard to the “axios error: network error” – looking online seems to imply latency issues – but outrs is a stand alone install… generic error?

monitoring using 

nvidia-smi

and 

inbuilt system monitor in ubuntu

we see cpu usage is mainly concentrated to a single core (there are 20) – although cuda reports gpu usage spikes at around 60% - memory (only 16GB) does max out just before the error happens…

your thoughts on working through this would be appreciated…

system being:

model name	: 12th Gen Intel(R) Core(TM) i7-12700F
16GB RAM
SSD
NVIDIA GeForce RTX 3060
NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5 

![pic](https://github.com/danbider/lightning-pose/assets/139504046/3e636009-cb60-48c8-a680-12a22a9e679e)

**Comment by themattinthehatt** [comment]
@Chrysovalantis000 would you mind opening this as in issue in the Pose-app repo? thanks!
https://github.com/Lightning-Universe/Pose-app/issues

**Comment by themattinthehatt** [comment]
closing, see duplicate issue at https://github.com/Lightning-Universe/Pose-app/issues/96
