### ISSUE TITLE
Error about varying image sizes in fully supervised model training

### ISSUE THREAD

**Issue by hummuscience** [danbider/lightning-pose#188]
I am on the main branch and using the dev pip install.

Running the training hydra script as usual and get the following error:

![Screenshot from 2024-07-17 10-06-58](https://github.com/user-attachments/assets/a5ad07fa-cb5c-47dd-b8d8-dcc030694f0c)

From what I understood, this error should not occur when using a fully supervised model (without pca or temporal losses).

This is related to the training of the Topvieemouse5k dataset, which has varying sizes: https://github.com/danbider/lightning-pose/issues/158

Btw, this error does not occur on the dynamic_crop branch.

**Comment by hummuscience** [comment]
I am a bit confused, as I was able to run this on the main brain a few days ago without getting this error. The only thing that changed was that I pulled the recent changes to the repo. So the error must have been quite recently, but I might be mistaken.

I switched to the dynamic_crop branch since it looks like this dependency on image size was merged there: https://github.com/danbider/lightning-pose/pull/117

**Comment by themattinthehatt** [comment]
Oh yes, my apologies - ok I recommend switching to the `unsuper-multiview` branch as this (1) has the ability to train on multiple image sizes; and (2) does not run the validation data through the augmentation pipeline.

This branch is now PR #187 which will be merged into `main` in the next day or so!
