### ISSUE TITLE
Converting Sleap data to Lightning Pose format

### ISSUE THREAD

**Issue by Freddie-Faulich** [danbider/lightning-pose#191]
Hello, Thanks for the great tool! I'm trying to label my data with Sleap and train it with your model, how do I convert it into the right format?

**Comment by themattinthehatt** [comment]
@Freddie-Faulich just a reminder that Lightning Pose is still only compatible with single-animal pose estimation. If that's still your use case, then you can easily convert from a `.pkg.slp` file to Lightning Pose format using this script: https://github.com/danbider/lightning-pose/blob/main/scripts/converters/sleap2lp.py

**Comment by agosztolai** [comment]
There is a typo in the file. --slp_file should be --slp_dir.
