### ISSUE TITLE
create  bi-directional converter from Lighting Pose and Label Studio.

### ISSUE THREAD

**Issue by robert-s-lee** [danbider/lightning-pose#45]
Please review Label Studio Setup [Instructions](https://github.com/robert-s-lee/lightning-pose/blob/label-studio/README.label-studio.md) 

A method to convert Lightning Pose Annotation data with Label Studio Annotation

Lightning Pose Annotation uses:
- [ToyMouseRunningData pngs](toy_datasets/toymouseRunningData/barObstacleScaling1)
- the pngs are annotated in [CSV](toy_datasets/toymouseRunningData/CollectedData_.csv)

Label Studio can [import pre-annotated data](https://labelstud.io/guide/predictions.html)
JSON-MIN version
```JSON
[
  {
    "img": "/data/upload/1/18928a62-img1.png",
    "id": 1,
    "kp-1": [
      {
        "x": 96.71717171717172,
        "y": 7.389162561576355,
        "width": 0.5050505050505051,
        "keypointlabels": [
          "Nose"
        ],
        "original_width": 396,
        "original_height": 406
      },
      {
        "x": 92.17171717171718,
        "y": 5.41871921182266,
        "width": 0.5050505050505051,
        "keypointlabels": [
          "Face"
        ],
        "original_width": 396,
        "original_height": 406
      }
    ],
    "annotator": 1,
    "annotation_id": 1,
    "created_at": "2022-07-06T12:49:47.101659Z",
    "updated_at": "2022-07-06T12:49:47.101700Z",
    "lead_time": 5.507
  }
]
```

TODO:

- [ ] convert toy_datasets/toymouseRunningData/CollectedData_.csv to label studio pre-annotated format for import

@kathleenislee https://github.com/robert-s-lee/lightning-pose/blob/label-studio/tests/utils/csv_to_label_studio.py has sample code to help get started that reads CSV.  the script needs to export in JSON-MIN format.

- [ ] convert  label studio pre-annotated  JSON to  toy_datasets/toymouseRunningData/CollectedData_.csv format

**Comment by themattinthehatt** [comment]
Superceded by updates [here](https://github.com/Lightning-AI/lightning-pose-app)
