### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by timsainb** [danbider/lightning-pose#85]
Hi Team,

Cool paper. 

This is a question not an issue: I'm considering trying out lightning pose on my data but was hoping you could provide some info on inference speed before I try it out. I didn't see anything in the paper. About how many frames/second are you able to transcribe after training? Do you have any benchmarks I missed?

Thanks,

**Comment by danbider** [comment]
@timsainb -- thanks for your interest. We haven't reported these metrics in the paper, but it's fast with NVIDIA DALI. FPS will depend on on image size (the resized image that goes into the network), and whether you use temporal context network or not. 
But for images resized to 256 X 256 with context, expect 400-1000 FPS during inference on a simple GPU machine

**Comment by danbider** [comment]
if speed is crucial for you I suggest training our baseline model first (a la DLC), and in the config, increasing `sequence_length` to as many video frames that can fit on your GPU
Then you could go to fancier variants and see if it's working well for you

**Comment by timsainb** [comment]
Awesome, thanks for the quick reply!
