### ISSUE TITLE
GPU memory requirements

### ISSUE THREAD

**Issue by MichaelGMoore** [danbider/lightning-pose#94]
Hello Lightning Pose,
I have a 12Gb RTX3060 GPU and I received a CUDA out-of-memory error when trying to run the "semi-supervised" model:

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 11.76 GiB total capacity; 9.16 GiB already allocated; 38.31 MiB free; 9.24 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

This was run using Pose-app/app.py. It was training a model based on a 180Mb video and 20 labeled frames with 4 keypoints. I could upgrade to a 24 Gb GPU if I knew that this would fix the issue. Is there a recommended GPU size for running Lightning-Pose?

**Comment by themattinthehatt** [comment]
@MichaelGMoore what is the frame size of your images/video? Maybe this is larger than what we have typically tested on. You can decrease the batch sizes by manually editing the config file, stored in `Pose-app/.shared/data/<proj_name>/model_config_<proj_name>.yaml

- training.train_batch_size: batch size for labeled data (same for val, test)
- dali.context.train.batch_size: batch size for unlabeled data during training
- dali.context.predict.sequence_length: batch size for unlabeled data during inference

In the future we will make it easier to adjust these settings directly from the app, thanks for bearing with us :)

**Comment by MichaelGMoore** [comment]
The video dimensions are 720 x 480.

**Comment by themattinthehatt** [comment]
ok yeah that's slightly larger than what we normally work with - in addition to changing batch size you could try automatically resizing the frames during training to something smaller (like 256x256 or 384x384) using the config file (data.image_resize_dims)

**Comment by MichaelGMoore** [comment]
After cropping+rescaling down to 256x256 it worked without errors and without changing any parameters. When I run "Video Diagnostics" with app.py, everything looks good. But I cannot find any saved .csv of the predictions on the full video. Alternatively, when I run "infer" on the full video, I do not see any option to save the results to file. Looking through the /Pose-App/Data folder also I don't see the results. Any suggestions?

**Comment by themattinthehatt** [comment]
You should be able to find all the data in `Pose-app/.shared/data/<proj_name>/models`. The models are organized by date/time, and if you go into one of the model folders you'll see `video_preds`, which contains video inference results for the videos you used for labeling, and `video_preds_infer`, which contains video inference results for the videos you ran inference on separately in the app. We'll definitely work on the documentation! Let me know if you're able to find everything.

**Comment by MichaelGMoore** [comment]
great thanks

**Comment by themattinthehatt** [comment]
Here's some more extensive documentation, let me know if this helps:
https://github.com/Lightning-Universe/Pose-app/blob/develop/docs/directory_structure.md

**Comment by MichaelGMoore** [comment]
Thank you. My first impression is that the semi-super model is a big improvement over the super model. The results from the super model seem similar to what we are used to getting from DeepLabCut. We will run some more tests and comparisons with DeepLabCut in the coming weeks. 

I have one small issue, when I launch "app.py" and "load existing project", it only gives me the 3 tabs up to "label frames". When the frames are already labeled there is nothing left to do, but I can't seem to figure out how to get it to unlock the remaining tabs.

**Comment by themattinthehatt** [comment]
Hmm so I don't see the same issue with "load existing project" on my end, all the tabs pop up - when did you last `git pull`? Maybe there are new updates? If you go into `app.py` at the bottom of the file you should see a method called `configure_layout` that looks like this:
```
        if self.extract_ui.proj_dir:
            return [
                project_tab,
                extract_tab,
                annotate_tab,
                train_tab,
                train_status_tab,
                st_frame_tab,
                st_video_tab,
                fo_prep_tab,
                fo_tab,
            ]
        else:
            return [
                project_tab,
            ]
```
Is that what you see?

**Comment by MichaelGMoore** [comment]
Yes, that is what I see. I will try to look for errors in the terminal stream when I load the project.

**Comment by MichaelGMoore** [comment]
To update, it seems the problems are worse than I thought. For example, when I create a new project, it no longer asks me to enter keypoint names and select keypoints for PCA. Instead it just tells me to go to extract frames tab. If I do that, I end up in Label Frames, but with the two default keypoints. I could try a fresh re-installation?

**Comment by themattinthehatt** [comment]
oh that's very unfortunate - I haven't run into this type of issue before. Yes, maybe a fresh installation is best, and if you continue to run into issues I'd be happy to meet up and try to debug with you.

**Comment by MichaelGMoore** [comment]
The fresh re-install has worked, I think we can close this issue.
